//Localhost
### Get home
https://localhost:3000/

### Get all contacts
http://localhost:3000/contacts/

### Get a single contact
http://localhost:3000/contacts/650c5812c06bc031e32200a1



//From Render
### Get home
https://cse-341-contacts.onrender.com/

### Get all contacts
https://cse-341-contacts.onrender.com/contacts/

### Get single contact
https://cse-341-contacts.onrender.com/contacts/650c5812c06bc031e32200a3